let me=null,products=[],categories=[],orders=[],settings={},productGalleryImages=[];
const $=id=>document.getElementById(id);
const money=n=>new Intl.NumberFormat('fr-DZ',{maximumFractionDigits:0}).format(Number(n)||0)+' DA';
const toast=m=>{$('toast').textContent=m;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2200)};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const slug=s=>s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
async function boot(){const x=await supabaseClient.auth.getSession();if(x.data.session){me=x.data.session.user;await enter()}else showAuth();supabaseClient.auth.onAuthStateChange((_e,s)=>{if(s){me=s.user;enter()}else showAuth()})}
function showAuth(){$('authView').hidden=false;$('notAdminView').hidden=true;$('dashboard').hidden=true;$('userArea').innerHTML=''}
async function enter(){const r=await supabaseClient.from('profiles').select('is_admin,full_name').eq('id',me.id).single();if(r.error||!r.data?.is_admin){$('authView').hidden=true;$('notAdminView').hidden=false;$('dashboard').hidden=true;$('notAdminEmail').textContent=me.email||'';$('userArea').innerHTML='<button class="btn ghost" id="headerLogout">Déconnexion</button>';$('headerLogout').onclick=logout;return}$('authView').hidden=true;$('notAdminView').hidden=true;$('dashboard').hidden=false;$('userArea').innerHTML='<span style="font-size:12px;color:#777">'+esc(r.data.full_name||me.email)+'</span> <button class="btn ghost" id="headerLogout">Déconnexion</button>';$('headerLogout').onclick=logout;await refreshAll()}
async function refreshAll(){await Promise.all([loadProducts(),loadCategories(),loadOrders(),loadSettings()]);renderStats();renderProducts();renderCategories();renderOrders();renderSettings();populateCategories()}
async function loadProducts(){const r=await supabaseClient.from('products').select('*,categories(name)').order('created_at',{ascending:false});if(r.error)return toast(r.error.message);products=r.data||[]}
async function loadCategories(){const r=await supabaseClient.from('categories').select('*').order('sort_order').order('name');if(r.error)return toast(r.error.message);categories=r.data||[]}
async function loadOrders(){const r=await supabaseClient.from('orders').select('*').order('created_at',{ascending:false});if(r.error)return toast(r.error.message);orders=r.data||[]}
async function loadSettings(){const r=await supabaseClient.from('site_settings').select('key,value');if(r.error)return toast(r.error.message);settings={};(r.data||[]).forEach(x=>settings[x.key]=x.value)}
function renderStats(){const active=products.filter(p=>p.is_active).length,pending=orders.filter(o=>o.status==='pending').length,stock=products.reduce((s,p)=>s+Number(p.stock_qty||0),0);$('stats').innerHTML='<div class="stat"><span>Produits actifs</span><strong>'+active+'</strong></div><div class="stat"><span>Produits totaux</span><strong>'+products.length+'</strong></div><div class="stat"><span>Commandes en attente</span><strong>'+pending+'</strong></div><div class="stat"><span>Stock total</span><strong>'+stock+'</strong></div>'}
function renderProducts(){$('productsTable').innerHTML=products.length?products.map(p=>'<tr><td><div class="product-cell">'+(p.image_url?'<img class="thumb" src="'+esc(p.image_url)+'">':'<div class="thumb"></div>')+'<div><b>'+esc(p.name)+'</b><small style="display:block;color:#888">'+esc(p.sku||'')+'</small></div></div></td><td>'+esc(p.categories?.name||'—')+'</td><td>'+money(p.price_dzd)+'</td><td>'+p.stock_qty+'</td><td><span class="status '+(p.is_active?'on':'')+'">'+(p.is_active?'Visible':'Masqué')+'</span></td><td><div class="actions"><button class="small-btn" data-edit="'+p.id+'">Modifier</button><button class="small-btn" data-toggle="'+p.id+'">'+(p.is_active?'Masquer':'Publier')+'</button><button class="small-btn danger" data-delete="'+p.id+'">Suppr.</button></div></td></tr>').join(''):'<tr><td colspan="6">Aucun produit.</td></tr>';document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openProduct(products.find(p=>p.id===b.dataset.edit)));document.querySelectorAll('[data-toggle]').forEach(b=>b.onclick=()=>toggleProduct(b.dataset.toggle));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>deleteProduct(b.dataset.delete))}
function renderCategories(){$('categoriesList').innerHTML=categories.map(c=>'<div class="list-row"><div><b>'+esc(c.name)+'</b><small style="display:block;color:#888">'+esc(c.description||'')+'</small></div><button class="small-btn" data-cat="'+c.id+'">'+(c.is_active?'Masquer':'Publier')+'</button></div>').join('');document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>toggleCategory(b.dataset.cat))}
function renderOrders(){$('ordersList').innerHTML=orders.length?orders.map(o=>'<article class="order-card"><div class="order-head"><div><h3>Commande #'+o.order_number+'</h3><p>'+esc(o.customer_name)+' · '+esc(o.phone)+'<br>'+esc(o.wilaya||'')+' '+esc(o.commune||'')+' · '+esc(o.address||'')+'</p></div><div class="order-controls"><select data-order="'+o.id+'"><option value="pending" '+(o.status==='pending'?'selected':'')+'>En attente</option><option value="confirmed" '+(o.status==='confirmed'?'selected':'')+'>Confirmée</option><option value="preparing" '+(o.status==='preparing'?'selected':'')+'>Préparation</option><option value="shipped" '+(o.status==='shipped'?'selected':'')+'>Expédiée</option><option value="delivered" '+(o.status==='delivered'?'selected':'')+'>Livrée</option><option value="cancelled" '+(o.status==='cancelled'?'selected':'')+'>Annulée</option></select></div></div><div class="order-items"><b>Total : '+money(o.total_dzd)+'</b><div style="margin-top:6px">Paiement : '+esc(o.payment_method)+'</div></div></article>').join(''):'<div class="empty">Aucune commande.</div>';document.querySelectorAll('[data-order]').forEach(s=>s.onchange=()=>updateStatus(s.dataset.order,s.value))}
function renderSettings(){$('settingsForm').store_name.value=settings.store_name||'TOP 1';$('settingsForm').whatsapp_phone.value=settings.whatsapp_phone||'';$('settingsForm').payment_method.value=settings.payment_method||'Paiement à la livraison'}
function populateCategories(){$('productCategory').innerHTML='<option value="">Sans catégorie</option>'+categories.map(c=>'<option value="'+c.id+'">'+esc(c.name)+'</option>').join('')}
async function openProduct(p){productGalleryImages=[];const f=$('productForm');f.reset();f.id.value=p?.id||'';f.name.value=p?.name||'';f.sku.value=p?.sku||'';f.category_id.value=p?.category_id||'';f.price_dzd.value=p?.price_dzd??'';f.compare_at_price_dzd.value=p?.compare_at_price_dzd??'';f.stock_qty.value=p?.stock_qty??0;f.description.value=p?.description||'';setOptionChecks('sizes_options',(p?.variant_options||{}).sizes||[]);setOptionChecks('colors_options',(p?.variant_options||{}).colors||[]);f.sizes_custom.value='';f.colors_custom.value='';f.specifications.value=formatSpecs(p?.specifications||{});f.is_active.checked=p?p.is_active:true;f.is_featured.checked=p?p.is_featured:false;$('productModalTitle').textContent=p?'Modifier le produit':'Ajouter un produit';$('currentImage').innerHTML=p?.image_url?'<img class="current-image" src="'+esc(p.image_url)+'">':'';$('productImages').value='';$('productGallery').innerHTML='';$('productModal').classList.add('open');if(p?.id)await renderProductGallery(p.id)}
function parseList(text){return String(text||'').split(',').map(s=>s.trim()).filter(Boolean)}
function setOptionChecks(name,values){const set=new Set((values||[]).map(String));document.querySelectorAll('input[name="'+name+'"]').forEach(el=>el.checked=set.has(el.value))}
function getSelectedOptions(name,custom){return Array.from(document.querySelectorAll('input[name="'+name+'"]:checked')).map(el=>el.value).concat(parseList(custom)).filter((v,i,a)=>a.indexOf(v)===i)}
function parseSpecs(text){const out={};String(text||'').split(/\n+/).forEach(line=>{const i=line.indexOf(':');if(i>0){const k=line.slice(0,i).trim(),v=line.slice(i+1).trim();if(k&&v)out[k]=v}});return out}
function formatSpecs(obj){return Object.entries(obj||{}).map(([k,v])=>k+': '+v).join('\n')}
async function renderProductGallery(pid){const r=await supabaseClient.from('product_images').select('*').eq('product_id',pid).order('sort_order').order('created_at');if(r.error){$('productGallery').innerHTML='<div class="gallery-note">'+esc(r.error.message)+'</div>';return}productGalleryImages=r.data||[];if(!productGalleryImages.length){$('productGallery').innerHTML='<div class="gallery-note">Aucune photo supplémentaire pour le moment.</div>';return}$('productGallery').innerHTML='<div class="gallery-title">Photos du produit</div><div class="admin-gallery">'+productGalleryImages.map((im,i)=>{const url=supabaseClient.storage.from('product-images').getPublicUrl(im.storage_path).data.publicUrl;return '<div class="admin-gallery-item"><img src="'+esc(url)+'" alt="'+esc(im.alt_text||'')+'"><div><small>'+(i===0?'Photo 1':'Photo '+(i+1))+'</small><button type="button" class="small-btn danger" data-img-delete="'+im.id+'">Suppr.</button></div></div>'}).join('')+'</div>';document.querySelectorAll('[data-img-delete]').forEach(b=>b.onclick=()=>deleteProductImage(b.dataset.imgDelete))}
async function deleteProductImage(id){if(!confirm('Supprimer cette photo ?'))return;const im=productGalleryImages.find(x=>x.id===id);if(!im)return;const rm=await supabaseClient.storage.from('product-images').remove([im.storage_path]);if(rm.error)return toast(rm.error.message);const r=await supabaseClient.from('product_images').delete().eq('id',id);if(r.error)return toast(r.error.message);const productId=im.product_id;const remaining=await supabaseClient.from('product_images').select('*').eq('product_id',productId).order('sort_order').order('created_at');const next=remaining.data?.[0];const nextUrl=next?supabaseClient.storage.from('product-images').getPublicUrl(next.storage_path).data.publicUrl:null;const p=products.find(x=>x.id===productId);if(p?.image_url===supabaseClient.storage.from('product-images').getPublicUrl(im.storage_path).data.publicUrl||(!p?.image_url&&nextUrl))await supabaseClient.from('products').update({image_url:nextUrl}).eq('id',productId);await renderProductGallery(productId);await loadProducts();renderProducts();toast('Photo supprimée')}
async function saveProduct(e){e.preventDefault();const f=new FormData(e.target),id=String(f.get('id')||''),name=String(f.get('name')||'').trim(),payload={name:name,slug:slug(name),sku:String(f.get('sku')||'').trim()||null,category_id:String(f.get('category_id')||'')||null,price_dzd:Number(f.get('price_dzd')),compare_at_price_dzd:f.get('compare_at_price_dzd')?Number(f.get('compare_at_price_dzd')):null,stock_qty:Number(f.get('stock_qty')),description:String(f.get('description')||''),variant_options:{sizes:getSelectedOptions('sizes_options',f.get('sizes_custom')),colors:getSelectedOptions('colors_options',f.get('colors_custom'))},specifications:parseSpecs(f.get('specifications')),is_active:f.get('is_active')==='on',is_featured:f.get('is_featured')==='on'};let r=id?await supabaseClient.from('products').update(payload).eq('id',id).select().single():await supabaseClient.from('products').insert(payload).select().single();if(r.error)return toast(r.error.message);const pid=r.data.id;const files=f.getAll('images').filter(x=>x&&x.size);let existing=[];if(files.length){const er=await supabaseClient.from('product_images').select('sort_order').eq('product_id',pid);existing=er.data||[]}let nextOrder=existing.reduce((m,x)=>Math.max(m,Number(x.sort_order)||0),-1)+1;let firstNewUrl=null;for(const file of files){const ext=(file.name.split('.').pop()||'jpg').toLowerCase().replace(/[^a-z0-9]/g,'')||'jpg';const path='products/'+pid+'/'+Date.now()+'-'+Math.random().toString(36).slice(2,8)+'.'+ext;const up=await supabaseClient.storage.from('product-images').upload(path,file,{upsert:false});if(up.error)return toast(up.error.message);const url=supabaseClient.storage.from('product-images').getPublicUrl(path).data.publicUrl;if(!firstNewUrl)firstNewUrl=url;const ir=await supabaseClient.from('product_images').insert({product_id:pid,storage_path:path,alt_text:name,sort_order:nextOrder++});if(ir.error)return toast(ir.error.message)}const current=products.find(x=>x.id===pid);if(!id&&!productGalleryImages.length&&firstNewUrl)await supabaseClient.from('products').update({image_url:firstNewUrl}).eq('id',pid);else if(id&&!current?.image_url&&firstNewUrl)await supabaseClient.from('products').update({image_url:firstNewUrl}).eq('id',pid);$('productModal').classList.remove('open');await loadProducts();renderProducts();renderStats();toast('Produit enregistré')}
async function toggleProduct(id){const p=products.find(x=>x.id===id);if(!p)return;const r=await supabaseClient.from('products').update({is_active:!p.is_active}).eq('id',id);if(r.error)return toast(r.error.message);await loadProducts();renderProducts();renderStats()}
async function deleteProduct(id){if(!confirm('Supprimer ce produit ?'))return;const imgs=await supabaseClient.from('product_images').select('storage_path').eq('product_id',id);const paths=(imgs.data||[]).map(x=>x.storage_path);if(paths.length)await supabaseClient.storage.from('product-images').remove(paths);const r=await supabaseClient.from('products').delete().eq('id',id);if(r.error)return toast(r.error.message);await loadProducts();renderProducts();renderStats();toast('Produit supprimé')}
async function saveCategory(e){e.preventDefault();const f=new FormData(e.target),name=String(f.get('name')).trim();const r=await supabaseClient.from('categories').insert({name:name,slug:slug(name),description:String(f.get('description')||'')});if(r.error)return toast(r.error.message);e.target.reset();await loadCategories();renderCategories();populateCategories();toast('Catégorie ajoutée')}
async function toggleCategory(id){const c=categories.find(x=>x.id===id);if(!c)return;const r=await supabaseClient.from('categories').update({is_active:!c.is_active}).eq('id',id);if(r.error)return toast(r.error.message);await loadCategories();renderCategories();populateCategories()}
async function updateStatus(id,status){const r=await supabaseClient.from('orders').update({status:status}).eq('id',id);if(r.error)return toast(r.error.message);await loadOrders();renderOrders();renderStats()}
async function saveSettings(e){e.preventDefault();for(const key of ['store_name','whatsapp_phone','payment_method']){const value=e.target[key].value,r=await supabaseClient.from('site_settings').upsert({key:key,value:value});if(r.error)return toast(r.error.message)}await loadSettings();toast('Réglages enregistrés')}
async function signIn(e){e.preventDefault();const r=await supabaseClient.auth.signInWithPassword({email:$('authEmail').value,password:$('authPassword').value});if(r.error)$('authMsg').textContent=r.error.message}
async function signUp(){const email=$('authEmail').value,password=$('authPassword').value;if(!email||password.length<6){$('authMsg').textContent='Entrez un email et un mot de passe de 6 caractères minimum.';return}const r=await supabaseClient.auth.signUp({email,password});$('authMsg').textContent=r.error?r.error.message:'Compte créé. Vérifiez votre email si demandé.'}
async function logout(){await supabaseClient.auth.signOut()}
$('authForm').onsubmit=signIn;$('signupBtn').onclick=signUp;$('logoutBtn1').onclick=logout;$('newProductBtn').onclick=()=>openProduct();$('closeProduct').onclick=()=>$('productModal').classList.remove('open');$('productForm').onsubmit=saveProduct;$('categoryForm').onsubmit=saveCategory;$('settingsForm').onsubmit=saveSettings;$('refreshOrders').onclick=async()=>{await loadOrders();renderOrders();renderStats()};document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tab-panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('tab-'+b.dataset.tab).classList.add('active')});boot();