let product=null,images=[],imageIndex=0,qty=1,settings={},selectedOptions={};
const $=id=>document.getElementById(id);const money=n=>new Intl.NumberFormat('fr-DZ',{maximumFractionDigits:0}).format(Number(n)||0)+' DA';const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));const toast=m=>{$('toast').textContent=m;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2200)};function imgUrl(path){return path?supabaseClient.storage.from('product-images').getPublicUrl(path).data.publicUrl:null}
async function load(){const id=new URLSearchParams(location.search).get('id');if(!id){showError('Produit introuvable.');return}const [p,s]=await Promise.all([supabaseClient.from('products').select('*,categories(name,slug)').eq('id',id).eq('is_active',true).single(),supabaseClient.from('site_settings').select('key,value')]);if(p.error||!p.data){showError('Ce produit n’est plus disponible.');return}product=p.data;(s.data||[]).forEach(x=>settings[x.key]=x.value);const g=await supabaseClient.from('product_images').select('*').eq('product_id',product.id).order('sort_order').order('created_at');images=(g.data||[]).map(x=>({url:imgUrl(x.storage_path),alt:x.alt_text||product.name}));if(product.image_url&&!images.some(x=>x.url===product.image_url))images.unshift({url:product.image_url,alt:product.name});render();await loadRelated();updateContact()}
function showError(m){$('productState').textContent=m}
function render(){document.title=product.name+' — TOP 1';$('pageTitle').textContent=product.name+' — TOP 1';$('metaDescription').setAttribute('content',(product.description||'Découvrez '+product.name)+' — TOP 1 Algérie.');$('productState').hidden=true;$('productContent').hidden=false;$('detailsSection').hidden=false;$('productName').textContent=product.name;$('productCategory').textContent=product.categories?.name||'Produit';$('productSku').textContent=product.sku?'SKU · '+product.sku:'';$('productBadge').hidden=!product.is_featured;$('productDescriptionShort').textContent=(product.description||'').split(/\n+/)[0]||'Découvrez les détails de ce produit TOP 1.';$('productPrice').textContent=money(product.price_dzd);if(product.compare_at_price_dzd&&Number(product.compare_at_price_dzd)>Number(product.price_dzd)){$('productCompare').textContent=money(product.compare_at_price_dzd);$('productCompare').hidden=false}else $('productCompare').hidden=true;const stock=Number(product.stock_qty||0);$('stockMessage').textContent=stock>0?(stock<5?'Plus que '+stock+' en stock.':'Disponible en stock.'):'Rupture de stock';$('stockMessage').classList.toggle('out',stock<=0);$('addToCart').disabled=stock<=0;$('buyNow').disabled=stock<=0;$('qtyPlus').disabled=stock<=0;renderVariantOptions();renderImages();$('fullDescription').textContent=product.description||'Aucune description détaillée pour le moment.';renderSpecs(product.specifications||{});$('year').textContent=new Date().getFullYear();$('qtyValue').textContent=qty}
function normalizeOptions(){const v=product?.variant_options||{};return {sizes:Array.isArray(v.sizes)?v.sizes.filter(Boolean):[],colors:Array.isArray(v.colors)?v.colors.filter(Boolean):[]}}
function renderVariantOptions(){
  const v=normalizeOptions(),groups=[];
  if(v.sizes.length)groups.push({key:'size',label:'Taille',values:v.sizes});
  if(v.colors.length)groups.push({key:'color',label:'Couleur',values:v.colors});
  const box=$('variantOptions');
  selectedOptions={};
  const available=Number(product.stock_qty||0)>0;
  if(!groups.length){
    box.innerHTML='';
    $('addToCart').disabled=!available;
    $('buyNow').disabled=!available;
    return;
  }
  box.innerHTML=groups.map(g=>'<div class="variant-group"><div class="variant-label">'+g.label+'</div><div class="variant-choices">'+g.values.map((value,i)=>'<div class="variant-choice"><input type="radio" id="opt-'+g.key+'-'+i+'" name="option-'+g.key+'" value="'+esc(value)+'"><label for="opt-'+g.key+'-'+i+'">'+esc(value)+'</label></div>').join('')+'</div></div>').join('')+'<div class="variant-hint" id="variantHint">Veuillez sélectionner '+groups.map(g=>g.label.toLowerCase()).join(' et ')+'.</div>';
  box.querySelectorAll('input').forEach(input=>{
    input.onchange=()=>{
      const type=input.name.replace('option-','');
      selectedOptions[type]=input.value;
      const missing=groups.filter(g=>!selectedOptions[g.key]);
      $('variantHint').textContent=missing.length?'Veuillez sélectionner '+missing.map(g=>g.label.toLowerCase()).join(' et ')+'.':'Sélection complète ✓';
      $('variantHint').style.color=missing.length?'#a33c3c':'#396c4b';
      $('addToCart').disabled=missing.length>0||!available;
      $('buyNow').disabled=missing.length>0||!available;
    };
  });
  $('addToCart').disabled=true;
  $('buyNow').disabled=true;
}
function requiredOptionsComplete(){const v=normalizeOptions();return (!v.sizes.length||selectedOptions.size)&&(!v.colors.length||selectedOptions.color)}
function renderImages(){const strip=$('thumbnailStrip');if(!images.length){$('mainImage').hidden=true;$('mainPlaceholder').hidden=false;$('imageCounter').hidden=true;$('prevImage').disabled=true;$('nextImage').disabled=true;strip.innerHTML='';return}$('mainImage').hidden=false;$('mainPlaceholder').hidden=true;$('imageCounter').hidden=images.length<2;$('prevImage').disabled=images.length<2;$('nextImage').disabled=images.length<2;showImage();strip.innerHTML=images.map((im,i)=>'<button class="thumb-btn '+(i===imageIndex?'active':'')+'" data-i="'+i+'" aria-label="Photo '+(i+1)+'"><img src="'+esc(im.url)+'" alt="'+esc(im.alt)+'"></button>').join('');strip.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>{imageIndex=Number(b.dataset.i);showImage();refreshThumbs()})}
function showImage(){if(!images.length)return;const im=images[imageIndex];$('mainImage').src=im.url;$('mainImage').alt=im.alt;$('imageCounter').textContent=(imageIndex+1)+' / '+images.length}
function refreshThumbs(){$('thumbnailStrip').querySelectorAll('.thumb-btn').forEach((b,i)=>b.classList.toggle('active',i===imageIndex))}
function renderSpecs(specs){const rows=Object.entries(specs).filter(([k,v])=>String(v).trim()!=='');$('specTable').innerHTML=rows.length?rows.map(([k,v])=>'<div class="spec-row"><span>'+esc(k)+'</span><span>'+esc(v)+'</span></div>').join(''):'<div class="spec-empty">Les spécifications seront ajoutées prochainement.</div>'}
async function loadRelated(){const r=await supabaseClient.from('products').select('id,name,price_dzd,image_url,is_featured,categories(name)').eq('is_active',true).neq('id',product.id).eq('category_id',product.category_id).limit(4);const list=r.data||[];if(!list.length)return;$('relatedSection').hidden=false;$('relatedGrid').innerHTML=list.map(p=>'<article class="related-card"><a href="product.html?id='+encodeURIComponent(p.id)+'"><div class="related-art">'+(p.image_url?'<img src="'+esc(p.image_url)+'" alt="'+esc(p.name)+'">':'<div class="placeholder">🛍️</div>')+'</div><div class="related-info"><small>'+esc(p.categories?.name||'Produit')+'</small><h3>'+esc(p.name)+'</h3><div class="related-price">'+money(p.price_dzd)+'</div></div></a></article>').join('')}
function addToCartNow(){const stock=Number(product.stock_qty||0);if(stock<=0)return toast('Produit indisponible.');if(!requiredOptionsComplete()){toast('Sélectionnez les options du produit.');return}qty=Math.min(qty,stock);const cart=JSON.parse(localStorage.getItem('top1_cart')||'[]');const optionsKey=JSON.stringify(selectedOptions);const hit=cart.find(x=>x.id===product.id&&JSON.stringify(x.selected_options||{})===optionsKey);if(hit)hit.qty=Math.min((hit.qty||0)+qty,stock);else cart.push({id:product.id,name:product.name,price:Number(product.price_dzd),image_url:product.image_url||images[0]?.url||null,qty,selected_options:{...selectedOptions}});localStorage.setItem('top1_cart',JSON.stringify(cart));updateCartCount();toast(product.name+' ajouté au panier')}
function buyNow(){if(!requiredOptionsComplete()){toast('Sélectionnez les options du produit.');return}addToCartNow();setTimeout(()=>location.href='index.html#featured',300)}
function updateCartCount(){const cart=JSON.parse(localStorage.getItem('top1_cart')||'[]');$('cartCount').textContent=cart.reduce((s,i)=>s+Number(i.qty||0),0)}
function updateContact(){const phone=(settings.whatsapp_phone||'213000000000').replace(/\D/g,'');$('whatsappFooter').href='https://wa.me/'+phone}
$('prevImage').onclick=()=>{if(!images.length)return;imageIndex=(imageIndex-1+images.length)%images.length;showImage();refreshThumbs()};$('nextImage').onclick=()=>{if(!images.length)return;imageIndex=(imageIndex+1)%images.length;showImage();refreshThumbs()};$('qtyMinus').onclick=()=>{qty=Math.max(1,qty-1);$('qtyValue').textContent=qty};$('qtyPlus').onclick=()=>{const stock=Number(product?.stock_qty||0);qty=Math.min(stock||1,qty+1);$('qtyValue').textContent=qty};$('addToCart').onclick=addToCartNow;$('buyNow').onclick=buyNow;document.querySelectorAll('.detail-tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.detail-tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.detail-panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('panel-'+b.dataset.tab).classList.add('active')});updateCartCount();load();