let products=[],categories=[],settings={},deliveryRates=[],cart=JSON.parse(localStorage.getItem('top1_cart')||'[]'),activeCategory='Tous',searchTerm='';
const money=n=>new Intl.NumberFormat('fr-DZ',{maximumFractionDigits:0}).format(Number(n)||0)+' DA';
const $=id=>document.getElementById(id);
function saveCart(){localStorage.setItem('top1_cart',JSON.stringify(cart))}
function toast(m){$('toast').textContent=m;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2200)}
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
async function loadStore(){const [c,p,s,d]=await Promise.all([supabaseClient.from('categories').select('*').order('sort_order').order('name'),supabaseClient.from('products').select('*,categories(name,slug)').eq('is_active',true).order('is_featured',{ascending:false}).order('sort_order').order('created_at',{ascending:false}),supabaseClient.from('site_settings').select('key,value'),supabaseClient.from('delivery_rates').select('wilaya_code,wilaya_name,delivery_price_dzd').eq('is_active',true).order('wilaya_code')]);if(c.error||p.error||s.error||d.error){console.error(c.error||p.error||s.error||d.error);$('productGrid').innerHTML='<div class="empty">Impossible de charger la boutique pour le moment.</div>';return}categories=c.data||[];products=p.data||[];deliveryRates=d.data||[];(s.data||[]).forEach(x=>settings[x.key]=x.value);renderCategories();renderFilters();renderProducts();renderCart();updateContact();if(new URLSearchParams(location.search).get('cart')==='1')setTimeout(openCart,250);if(localStorage.getItem('top1_open_checkout')==='1'){localStorage.removeItem('top1_open_checkout');setTimeout(openCheckout,250)}}
function categoryEmoji(name=''){const n=name.toLowerCase();if(n.includes('jouet'))return '🧩';if(n.includes('work'))return '🦺';if(n.includes('vêtement')||n.includes('vetement'))return '👕';if(n.includes('cuisine'))return '🍴';return '🏠'}
function renderCategories(){const g=$('categoryGrid');g.innerHTML=categories.map((c,i)=>'<button class="category-card cat-'+(i%5)+'" data-cat="'+c.id+'"><span>0'+(i+1)+'</span><div><small>UNIVERS</small><h3>'+escapeHtml(c.name)+'</h3><p>'+escapeHtml(c.description||'Découvrez notre sélection.')+'</p></div><b>↗</b></button>').join('');g.querySelectorAll('.category-card').forEach(b=>b.addEventListener('click',()=>{activeCategory=b.dataset.cat;renderFilters();renderProducts();document.querySelector('#featured').scrollIntoView({behavior:'smooth'})}))}
function renderFilters(){const f=$('filters');f.innerHTML='<button class="filter '+(activeCategory==='Tous'?'active':'')+'" data-filter="Tous">Tous</button>'+categories.map(c=>'<button class="filter '+(activeCategory===c.id?'active':'')+'" data-filter="'+c.id+'">'+escapeHtml(c.name)+'</button>').join('');f.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>{activeCategory=b.dataset.filter;renderFilters();renderProducts()}))}
function renderProducts(){const q=searchTerm.trim().toLowerCase();let list=products;if(activeCategory!=='Tous')list=list.filter(p=>p.category_id===activeCategory);if(q)list=list.filter(p=>p.name.toLowerCase().includes(q)||(p.description||'').toLowerCase().includes(q)||(p.categories?.name||'').toLowerCase().includes(q));const g=$('productGrid');if(!list.length){g.innerHTML='<div class="empty">Aucun produit ne correspond à votre recherche.</div>';return}g.innerHTML=list.map(p=>{const img=p.image_url?'<img src="'+escapeHtml(p.image_url)+'" alt="'+escapeHtml(p.name)+'">':'<div class="placeholder">'+categoryEmoji(p.categories?.name)+'</div>';const hasOptions=(p.variant_options?.sizes?.length||p.variant_options?.colors?.length);return '<article class="product-card" data-product="'+p.id+'" role="link" tabindex="0"><div class="product-art">'+(p.is_featured?'<span class="badge">TOP 1</span>':'')+img+'</div><div class="product-info"><a class="product-link" href="product.html?id='+encodeURIComponent(p.id)+'"><small>'+escapeHtml(p.categories?.name||'CATÉGORIE')+'</small><h3>'+escapeHtml(p.name)+'</h3></a><div class="product-meta"><span class="price">'+money(p.price_dzd)+'</span><button class="add-btn" data-add="'+p.id+'">'+(hasOptions?'Choisir':'Ajouter +')+'</button></div></div></article>'}).join('');g.querySelectorAll('.product-card').forEach(card=>{const go=()=>{location.href='product.html?id='+encodeURIComponent(card.dataset.product)};card.addEventListener('click',e=>{if(e.target.closest('.add-btn')||e.target.closest('a'))return;go()});card.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&!e.target.closest('button')&&!e.target.closest('a')){e.preventDefault();go()}})});g.querySelectorAll('[data-add]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();const p=products.find(x=>x.id===b.dataset.add);const hasOptions=(p?.variant_options?.sizes?.length||p?.variant_options?.colors?.length);if(hasOptions)location.href='product.html?id='+encodeURIComponent(b.dataset.add);else addCart(b.dataset.add)}))}
function addCart(id){const p=products.find(x=>x.id===id);if(!p)return;const hit=cart.find(x=>x.id===id);if(hit)hit.qty++;else cart.push({id:p.id,name:p.name,price:Number(p.price_dzd),image_url:p.image_url,qty:1});saveCart();renderCart();toast(p.name+' ajouté au panier')}
function renderCart(){const count=cart.reduce((s,i)=>s+i.qty,0);$('cartCount').textContent=count;const box=$('cartItems');if(!cart.length){box.innerHTML='<div class="empty">Votre panier est vide.</div>';$('cartTotal').textContent='0 DA';return}box.innerHTML=cart.map((i,idx)=>'<div class="cart-row"><div class="cart-thumb">'+(i.image_url?'<img src="'+escapeHtml(i.image_url)+'" alt="">':'🛍️')+'</div><div><h4>'+escapeHtml(i.name)+'</h4>'+(i.selected_options&&Object.keys(i.selected_options).length?'<small class="cart-options">'+Object.entries(i.selected_options).map(([k,v])=>escapeHtml(k==='size'?'Taille':'Couleur')+': '+escapeHtml(v)).join(' · ')+'</small>':'')+'<small>'+money(i.price)+'</small><div class="qty"><button data-minus="'+idx+'">−</button><b>'+i.qty+'</b><button data-plus="'+idx+'">+</button></div></div><strong>'+money(i.price*i.qty)+'</strong></div>').join('');$('cartTotal').textContent=money(cart.reduce((s,i)=>s+i.price*i.qty,0));box.querySelectorAll('[data-minus]').forEach(b=>b.onclick=()=>changeQty(b.dataset.minus,-1));box.querySelectorAll('[data-plus]').forEach(b=>b.onclick=()=>changeQty(b.dataset.plus,1))}
function changeQty(index,d){const i=cart[Number(index)];if(!i)return;i.qty+=d;if(i.qty<=0)cart.splice(Number(index),1);saveCart();renderCart()}
function openCart(){$('cartDrawer').classList.add('open');$('overlay').classList.add('open')}
function closeCart(){$('cartDrawer').classList.remove('open');$('overlay').classList.remove('open')}
function renderCheckoutItems(){const box=$('checkoutItems');box.innerHTML=cart.map(i=>'<div class="checkout-item"><div><strong>'+escapeHtml(i.name)+'</strong>'+(i.selected_options&&Object.keys(i.selected_options).length?'<small>'+Object.entries(i.selected_options).map(([k,v])=>escapeHtml(k==='size'?'Taille':'Couleur')+': '+escapeHtml(v)).join(' · ')+'</small>':'')+'</div><span>'+i.qty+' × '+money(i.price)+'</span></div>').join('')}
function checkoutSubtotal(){return cart.reduce((s,i)=>s+i.price*i.qty,0)}
function selectedDeliveryRate(){return deliveryRates.find(x=>x.wilaya_code===$('checkoutWilaya').value)||null}
function updateCheckoutCalculator(){const subtotal=checkoutSubtotal(),rate=selectedDeliveryRate();$('checkoutSubtotal').textContent=money(subtotal);if(!rate||rate.delivery_price_dzd===null||rate.delivery_price_dzd===undefined){$('checkoutDelivery').textContent='—';$('checkoutTotal').textContent=money(subtotal);$('deliveryHint').textContent=$('checkoutWilaya').value?'Tarif de livraison à confirmer pour cette wilaya.':'Choisissez votre wilaya pour calculer les frais de livraison.';$('checkoutSubmit').disabled=true;return}const delivery=Number(rate.delivery_price_dzd);$('checkoutDelivery').textContent=money(delivery);$('checkoutTotal').textContent=money(subtotal+delivery);$('deliveryHint').textContent='Livraison vers '+rate.wilaya_name+' : '+money(delivery);$('checkoutSubmit').disabled=false}
function populateCheckoutWilayas(){const select=$('checkoutWilaya');select.innerHTML='<option value="">Choisissez votre wilaya</option>'+deliveryRates.map(r=>'<option value="'+escapeHtml(r.wilaya_code)+'">'+escapeHtml(r.wilaya_code)+' — '+escapeHtml(r.wilaya_name)+'</option>').join('');select.onchange=updateCheckoutCalculator}
function openCheckout(){if(!cart.length){toast('Votre panier est vide.');return}populateCheckoutWilayas();renderCheckoutItems();updateCheckoutCalculator();$('checkoutModal').classList.add('open')}
function closeCheckout(){$('checkoutModal').classList.remove('open')}
async function placeOrder(e){e.preventDefault();const f=new FormData(e.target),rate=selectedDeliveryRate();if(!rate||rate.delivery_price_dzd===null||rate.delivery_price_dzd===undefined){toast('Choisissez une wilaya pour calculer la livraison.');return}const {data,error}=await supabaseClient.rpc('place_order',{p_customer_name:String(f.get('customer_name')),p_phone:String(f.get('phone')),p_wilaya:String(f.get('wilaya')),p_commune:String(f.get('commune')||''),p_address:String(f.get('address')||''),p_notes:String(f.get('notes')||''),p_items:cart.map(i=>({product_id:i.id,quantity:i.qty,selected_options:i.selected_options||{}}))});if(error){toast(error.message||'Impossible de créer la commande.');return}const phone=(settings.whatsapp_phone||'213000000000').replace(/\D/g,'');const optionLines=cart.map(i=>{const opts=i.selected_options&&Object.keys(i.selected_options).length?' ['+Object.entries(i.selected_options).map(([k,v])=>(k==='size'?'Taille':'Couleur')+': '+v).join(', ')+']':'';return '• '+i.name+opts+' × '+i.qty}).join('\n');const msg=encodeURIComponent('Bonjour TOP 1, ma commande #'+(data?.order_number||'')+' vient d’être enregistrée.\nWilaya : '+(data?.wilaya||rate.wilaya_name)+'\nProduits : '+money(data?.subtotal_dzd)+'\nLivraison : '+money(data?.delivery_dzd)+'\nTotal : '+money(data?.total_dzd)+'\n'+optionLines+'\nNom : '+f.get('customer_name')+'. Téléphone : '+f.get('phone')+'.');cart=[];saveCart();renderCart();closeCheckout();closeCart();toast('Commande #'+(data?.order_number||'')+' enregistrée !');setTimeout(()=>window.open('https://wa.me/'+phone+'?text='+msg,'_blank'),500)}
function updateContact(){const phone=(settings.whatsapp_phone||'213000000000').replace(/\D/g,'');$('whatsappFooter').href='https://wa.me/'+phone}
$('cartBtn').onclick=openCart;$('closeCart').onclick=closeCart;$('overlay').onclick=()=>{closeCart();closeCheckout()};$('checkoutBtn').onclick=openCheckout;$('closeCheckout').onclick=closeCheckout;$('checkoutForm').onsubmit=placeOrder;$('searchBtn').onclick=()=>{const b=$('searchBar');b.hidden=!b.hidden;if(!b.hidden)$('searchInput').focus()};$('searchInput').oninput=e=>{searchTerm=e.target.value;renderProducts()};$('mobileMenuBtn').onclick=()=>$('mainNav').classList.toggle('open');$('newsletterForm').onsubmit=e=>{e.preventDefault();toast('Merci !');e.target.reset()};$('year').textContent=new Date().getFullYear();loadStore();